# Generated by Django 3.1 on 2021-05-17 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(default='0')),
                ('institute', models.CharField(default='Not provided', max_length=30)),
                ('degree', models.CharField(default='Not provided', max_length=30)),
                ('Number_of_publications', models.IntegerField(default='0')),
                ('funding', models.IntegerField(default='4 m', max_length=30)),
                ('type_of_funding', models.CharField(default='private', max_length=30)),
                ('Number_of_patents', models.IntegerField(default='nil', max_length=30)),
                ('license', models.CharField(default='nil', max_length=30)),
                ('Project_title', models.CharField(default='No projects have been added', max_length=100)),
                ('Project_details', models.CharField(default='No project details have been added', max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
